services:
  mailhog:
    container_name: ${APP_MAILHOG_CONTAINER}
    restart: always
    depends_on:
      - web
    image: mailhog/mailhog
    ports:
      - ${APP_MAILHOG_SMTP_PORT}:1025
      - ${APP_MAILHOG_WEB_PORT}:8025
    networks:
      - ${APP_NETWORK_NAME}
    env_file:
      - path: $PWD/.env.app
        required: true
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
