services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
  db:
    extends:
      file: docker-compose.base.yml
      service: db
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  phpmyadmin:
    extends:
      file: docker-compose.base.yml
      service: phpmyadmin
  mailhog:
    extends:
      file: docker-compose.base.yml
      service: mailhog
  web:
    image: caddy:latest
    container_name: laravel_web
    restart: unless-stopped
    volumes:
      - ./docker/caddy/CaddyFile:/etc/caddy/Caddyfile:ro
      - ./docker/caddy/security.conf:/etc/caddy/security
      - app_volume:/srv
      - ./docker/caddy/data:/data
      - ./docker/caddy/config:/config
    networks:
      - laravel_net
    depends_on:
      - app
    environment:
      - TZ=America/Manaus
    ports:
      - "${HTTP_PORT}:80"
      - "443:443"
    expose:
      - 80 # http
      - 443 # https
volumes:
  cache:
    driver: local
  app_volume:
    name: app_volume
    driver_opts:
      type: none
      o: bind
      device: $PWD/app
networks:
  laravel_net:
    name: laravel_net
    driver: bridge
