# Multi services entry point
#
# To check the running services run the command:
# docker ps | egrep 'app_|tools_' 
# or
# docker stats --no-stream | egrep 'app_|tools_'

# To check the stdout logs of a service run the command:
# docker logs -f <container_name>
#
# To check the health log of a service run the command:
# docker inspect -f '{{json .State.Health.Log}}' <container_name> | jq
#

# Build time is the time to build the entire project from scratch.;
# Download using a 500Mbps connection, VM 6vCPU, 16GB RAM, SSD disk.
# A average build time table is as follows:
# For php 8.4-fpm.debian: 2m 54s - 
# For php 8.4-fpm.alpine: 4m 00s - Final size 269Mb
# For php 8.4-fpm.distro: 1m 37s - Final size 509Mb
include:
  - docker-compose.tools.yml
services:
  app:
    extends:
      file: ./services/php/docker-compose.yml
      service: app
    depends_on:
      db:
        condition: service_healthy
      portainer:
        condition: service_started
      mailpit:
        condition: service_started
      redis:
        condition: service_healthy
  web:
    extends:
      file: ./services/$WEB_SERVER/docker-compose.yml
      service: web
    depends_on:
      - app
      - portainer
      - traefik
  db:
    extends:
      file: ./services/$DATABASE/docker-compose.yml
      service: db
  dbadmin:
    extends:
      file: ./services/$DATABASE/docker-compose.yml
      service: dbadmin
    depends_on:
      db:
        condition: service_healthy
volumes:
  cache:
    name: redis_cache
    driver: local
  # This volume mounts the host's ./app directory into containers.
  # It is defined as a top-level volume to be easily reusable across services.
  app_volume:
    name: app_volume
    driver_opts:
      type: none
      o: bind
      device: $PWD/app
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
    attachable: true
    enable_ipv4: true
    enable_ipv6: false
secrets:
  db_root_password:
    file: ./docker-data/$DATABASE/db_root_password.txt
