services:
  app:
    extends:
      file: $PWD/services/php/docker-compose.yml
      service: app
  db:
    extends:
      file: $PWD/services/$DATABASE/docker-compose.yml
      service: db
  dbadmin:
    extends:
      file: $PWD/services/$DATABASE/docker-compose.yml
      service: dbadmin
  redis:
    extends:
      file: $PWD/services/redis/docker-compose.yml
      service: redis
  smtp:
    extends:
      file: $PWD/services/mailpit/docker-compose.yml
      service: smtp
  web:
    extends:
      file: $PWD/services/$WEB_SERVER/docker-compose.yml
      service: web
volumes:
  cache:
    name: redis_cache
    driver: local
  app_volume:
    name: app_volume
    driver_opts:
      type: none
      o: bind
      device: $PWD/app
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
secrets:
  db_root_password:
    file: $PWD/docker-data/$DATABASE/db_root_password.txt
