services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
  db:
    extends:
      file: docker-compose.base.yml
      service: db
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  phpmyadmin:
    extends:
      file: docker-compose.base.yml
      service: phpmyadmin
  mailhog:
    extends:
      file: docker-compose.base.yml
      service: mailhog
  web:
    image: nginx:alpine
    container_name: laravel_web
    volumes:
      - app_volume:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net
    environment:
      - TZ=America/Manaus
    ports:
      - "$HTTP_PORT:80"
volumes:
  cache:
    driver: local
  app_volume:
    name: app_volume
    driver_opts:
      type: none
      o: bind
      device: $PWD/app
networks:
  laravel_net:
    name: laravel_net
    driver: bridge
