services:
  app:
    build:
      context: .
      dockerfile: docker-data/php/Dockerfile
    container_name: docker_php
    user: 1000:1000
    working_dir: /var/www
    volumes:
      - app_volume:/var/www
    depends_on:
      - db
      - redis
    networks:
      - app_net
  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - laravel_net
  mailhog:
    container_name: laravel_mailhog
    restart: always
    depends_on:
      - web
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel_net
