services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_php
    user: 1000:1000
    working_dir: /var/www
    volumes:
      - app_volume:/var/www
    depends_on:
      - db
      - redis
    networks:
      - laravel_net
  db:
    image: mysql:8
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./docker/mysql/mysqldata:/var/lib/mysql
    networks:
      - laravel_net
  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - laravel_net
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_myadmin
    restart: always
    depends_on:
      - db
      - web
    environment:
      PMA_ABSOLUTE_URI: "https://phpmyadmin.localhost/"
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: "secret"
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 2G
      MAX_EXECUTION_TIME: 600
    expose:
      - 80
    networks:
      - laravel_net
  mailhog:
    container_name: laravel_mailhog
    restart: always
    depends_on:
      - web
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel_net
