services:
  web:
    image: caddy:latest
    container_name: ${APP_CADDY_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - $PWD/caddy/CaddyFile:/etc/caddy/Caddyfile:ro
      - $PWD/caddy/security.conf:/etc/caddy/security
      - app_volume:/srv
      - $PWD/docker-data/caddy/data:/data
      - $PWD/docker-data/caddy/config:/config
    networks:
      - ${APP_NETWORK_NAME}
    depends_on:
      - app
    environment:
      TZ: ${APP_TIMEZONE}
    ports:
      - "${APP_HTTP_PORT}:80"
      - "443:443"
    expose:
      - 80 # http
      - 443 # https
volumes:
  app_volume:
    name: app_volume
    driver_opts:
      type: none
      o: bind
      device: $PWD/app
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
