services:
  db:
    image: ${MYSQL_IMAGE}:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password" # openssl rand -base64 20 | sudo docker secret create db_root_password -
      MYSQL_DATABASE: ${APP_DATABASE_NAME}
      MYSQL_USER: ${APP_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      TZ: ${APP_TIMEZONE}
    secrets:
      - db_root_password
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - 3306
    volumes:
      - ${MYSQLDATA_PATH}:/var/lib/mysql
    networks:
      - ${APP_NETWORK_NAME}
  dbadmin:
    extends:
      file: $PWD/services/phpmyadmin/docker-compose.yml
      service: dbadmin
secrets:
  db_root_password:
    file: $PWD/docker-data/mysql/db_root_password.txt
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
