## traefik.yml

accesslog:
  addInternals: true
  filePath: "/etc/traefik/access.log"

log:
  level: DEBUG
  filePath: /etc/traefik/traefik.log
# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  secure-web:
    address: ":443"