services:
  web:
    image: ${NGINX_IMAGE:-nginx}:${NGINX_VERSION}
    container_name: ${APP_NGINX_CONTAINER_NAME}
    volumes:
      - app_volume:/var/www
      - $PWD/services/nginx/conf/conf.d:/etc/nginx/conf.d
      - $PWD/services/nginx/conf/sites-enabled:/etc/nginx/sites-enabled
      - $PWD/services/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/docker-data/nginx/logs:/var/log/nginx/
    networks:
      - ${APP_NETWORK_NAME}
    environment:
      TZ: ${APP_TIMEZONE}
    ports:
      - "${APP_HTTP_PORT}:80"
    expose:
      - 80
volumes:
  app_volume:
    name: app_volume
    driver_opts:
      type: none
      o: bind
      device: $PWD/app
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
