services:
  web:
    image: nginx:alpine
    container_name: ${APP_NGINX_CONTAINER_NAME}
    volumes:
      - app_volume:/var/www
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ${APP_NETWORK_NAME}
    environment:
      TZ: ${APP_TIMEZONE}
    ports:
      - "${APP_HTTP_PORT}:80"
volumes:
  app_volume:
    name: app_volume
    driver_opts:
      type: none
      o: bind
      device: $PWD/app
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
