# ENV variables for this service.
# The content is available in .env.caddy with default values
#
# CADDY_IMAGE - The base image name for use. Default is caddy .
# CADDY_VERSION - The version tag for use. Default is alpine . RECOMMENDED TAGS[latest, alpine]
# APP_CADDY_CONTAINER_NAME - The container name
# APP_TIMEZONE - The user Timezone.
# APP_NETWORK_NAME - The network name of the docker services to be used.
# APP_HTTP_PORT - The http host port.
# APP_HTTPS_PORT - The https host port.
# PWD - The context directory(usualy the root path of the cloned project)
#
# You can start this service using the following command at the root of the cloned project:
#
# sudo PWD=${PWD} docker compose --env-file services/caddy/.env.caddy -f services/caddy/docker-compose.yml up -d
#
services:
  web:
    image: ${CADDY_IMAGE}:${CADDY_VERSION}
    container_name: ${APP_CADDY_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - $PWD/services/caddy/conf/CaddyFile:/etc/caddy/Caddyfile:ro
      - $PWD/services/caddy/services/:/etc/caddy/services/
      - $PWD/services/caddy/sites/:/etc/caddy/sites/
      - $PWD/services/caddy/snippets/:/etc/caddy/snippets/
      - $PWD/services/caddy/conf/security.conf:/etc/caddy/security
      - app_volume:/srv
      - $PWD/docker-data/caddy/data:/data
      - $PWD/docker-data/caddy/config:/config
    networks:
      - ${APP_NETWORK_NAME}
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${APP_TIMEZONE}
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
      - "${APP_HTTPS_PORT}:443/udp"
    expose:
      - 80 # http
      - 443 # https
volumes:
  app_volume:
    name: app_volume
    driver_opts:
      type: none
      o: bind
      device: $PWD/app
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
