# Container running the Redis instance.
#
# You can spin a standalone version with the default variables or using the .env.redis in this folder for custom values.
# Ex: docker composer -f services/redis/docker-compose.yml up -d
# or using the .env.redis
# docker composer -f services/redis/docker-compose.yml --env-file services/redis/.env.redis up -d
#
services:
  redis:
    image: ${REDIS_IMAGE:-redis}:${REDIS_VERSION:-latest}
    container_name: ${REDIS_CONTAINER:-app_redis}
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping | grep PONG
      interval: 10s
      timeout: 3s
      retries: 3
    environment:  # TODO: Improve security
      TZ: ${APP_TIMEZONE:-America/Sao_Paulo}
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - ${APP_REDIS_PORT:-6379}:6379
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - ${APP_NETWORK_NAME:-app_network}
    mem_reservation: "50M"
    mem_limit: "${REDIS_MEM_LIMIT:-500M}"
volumes:
  cache:
    name: redis_cache
    driver: local
networks:
  app_network:
    name: ${APP_NETWORK_NAME:-app_network}
    driver: bridge
