# Container to run the PHPMyAdmin instance used to manage the MySQL/MariaDB when selected.
# Default address via proxy http://dbadmin.localhost:8000 
# or
# Default address for standalone service http://127.0.0.1:9000
#
# You can spin a standalone version with the default variables or using the .env.phpmyadmin in this folder for custom values.
# Ex: docker composer -f services/phpmyadmin/docker-compose.yml up -d
# or using the .env.phpmyadmin
# docker composer -f services/phpmyadmin/docker-compose.yml --env-file services/phpmyadmin/.env.phpmyadmin up -d
#
x-dbadmin-traefik: &labels-traefik-dbadmin
  labels:
    - "traefik.enable=false"
    #- "traefik.http.routers.dbadmin.rule=Host(`dbadmin.localhost`)"
    #- "traefik.http.routers.dbadmin.entrypoints=web"
    #- "traefik.http.services.dbadmin.loadbalancer.server.port=9000"

services:
  dbadmin:
    image: ${PHPMYADMIN_IMAGE:-phpmyadmin}:${PHPMYADMIN_VERSION:-latest}
    container_name: ${PHPMYADMIN_CONTAINER_NAME:-app_phpmyadmin}
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --output-document=/dev/null http://127.0.0.1:9000 &> /dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 0s
    << : *labels-traefik-dbadmin
    environment:
      PMA_ARBITRARY: ${PHPMYADMIN_ARBITRARY:-1} # TODO: Check a way to not load the content below when arbitrary is 1
      PMA_ABSOLUTE_URI: ${PHPMYADMIN_URL:-http://127.0.0.1:9000}
      PMA_HOST: ${DB_HOST:-db}
      PMA_USER: ${APP_MYSQL_USER:-app}
      PMA_PASSWORD: ${APP_MYSQL_PASSWORD:-secret}
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 2G
      MAX_EXECUTION_TIME: 600
      APACHE_PORT: 9000
      PMA_PORT: ${MYSQL_PORT:-3306}
      TZ: ${APP_TIMEZONE:-America/Sao_Paulo}
    ports:
      - 9000:9000
    expose:
      - 9000
    networks:
      - ${APP_NETWORK_NAME:-app_network}
networks:
  app_network:
    name: ${APP_NETWORK_NAME:-app_network}
    driver: bridge
