services:
  dbadmin:
    image: ${PHPMYADMIN_IMAGE}:${PHPMYADMIN_VERSION}
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    restart: always
    depends_on:
      - db
    environment:
      PMA_ABSOLUTE_URI: ${PHPMYADMIN_URL}
      PMA_HOST: db
      PMA_USER: ${APP_MYSQL_USER}
      PMA_PASSWORD: ${APP_MYSQL_PASSWORD}
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 2G
      MAX_EXECUTION_TIME: 600
      APACHE_PORT: 9000
      PMA_PORT: ${MYSQL_PORT}
      TZ: ${APP_TIMEZONE}
    ports:
      - 9000:9000
    expose:
      - 9000
    networks:
      - ${APP_NETWORK_NAME}
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
