services:
  dbadmin:
    image: ${PHPMYADMIN_IMAGE:-phpmyadmin}:${PHPMYADMIN_VERSION:-latest}
    container_name: ${PHPMYADMIN_CONTAINER_NAME:-app_phpmyadmin}
    restart: always
    environment:
      PMA_ABSOLUTE_URI: ${PHPMYADMIN_URL:-http://127.0.0.1:9000}
      PMA_HOST: ${DB_HOST:-db}
      PMA_USER: ${APP_MYSQL_USER:-app}
      PMA_PASSWORD: ${APP_MYSQL_PASSWORD:-secret}
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 2G
      MAX_EXECUTION_TIME: 600
      APACHE_PORT: 9000
      PMA_PORT: ${MYSQL_PORT:-3306}
      PMA_ARBITRARY: ${PHPMYADMIN_ARBITRARY:-1}
      TZ: ${APP_TIMEZONE:-America/Sao_Paulo}
    ports:
      - 9000:9000
    expose:
      - 9000
    networks:
      - ${APP_NETWORK_NAME:-app_network}
networks:
  app_network:
    name: ${APP_NETWORK_NAME:-app_network}
    driver: bridge
