services:
  app:
    build:
      context: .
      dockerfile: $PWD/services/php/versions/Dockerfile.php${PHP_VERSION}-fpm
    container_name: ${APP_CONTAINER_NAME}
    user: 1000:1000
    working_dir: /var/www
    volumes:
      - app_volume:/var/www
      - $PWD/services/php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - $PWD/services/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      TZ: ${APP_TIMEZONE}
    networks:
      - ${APP_NETWORK_NAME}
    expose:
      - 9000 # The PHP service runs only in the internal app_network at the 9000
volumes:
  app_volume:
    name: app_volume
    driver_opts:
      type: none
      o: bind
      device: $PWD/app
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
