services:
  db:
    image: ${MARIADB_IMAGE}:${MARIADB_VERSION}
    container_name: ${MARIADB_CONTAINER_NAME}
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db_root_password)" --silent']
      #test: ["CMD", "mysql", "-u", "root", -p$$(cat /run/secrets/db_root_password), "--execute", "SHOW DATABASES;"] # Alternative healthcheck
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
    environment:
      MARIADB_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password" # openssl rand -base64 20 | sudo docker secret create db_root_password -
      MARIADB_DATABASE: ${APP_DATABASE_NAME}
      MARIADB_USER: ${APP_MYSQL_USER}
      MARIADB_PASSWORD: ${APP_MYSQL_PASSWORD}
      MARIADB_ROOT_HOST: "%"
      TZ: ${APP_TIMEZONE}
    secrets:
      - db_root_password
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - 3306
    volumes:
      - ${MARIADBDATA_PATH}:/var/lib/mysql
      - $PWD/services/mariadb/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    networks:
      - ${APP_NETWORK_NAME}
  dbadmin:
    extends:
      file: $PWD/services/phpmyadmin/docker-compose.yml
      service: dbadmin
secrets:
  db_root_password:
    file: $PWD/docker-data/mariadb/db_root_password.txt
networks:
  app_network:
    name: ${APP_NETWORK_NAME}
    driver: bridge
