# Container running the MariaDB 
# Note: The volumes at this container are refered at the root folder of the project.
# Befor running this service run the command at the root folder:
# openssl rand -base64 20 > docker-data/mariadb/db_root_password.txt
# Run the service at the root folder using the -f flag. 
# Ex: docker compose -f services/mariadb/docker-compose.yml --env-file services/mariadb/.env.mariadb up -d
#
# Default host port is 3306 and can be changed with the env variables.
# This service runs with PHPMyAdmin for easy management of the database.
# The PHPMyAdmin default address is http://127.0.0.1:9000 if used standalone
# or
# Via proxy http://dbadmin.localhost:8000 
#
services:
  db:
    image: ${MARIADB_IMAGE:-mariadb}:${MARIADB_VERSION:-lts}
    container_name: ${MARIADB_CONTAINER_NAME:-app_mariadb}
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mariadb-admin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db_root_password)" --silent']
      #test: ["CMD", "mariadb", "-u", "root", -p$$(cat /run/secrets/db_root_password), "--execute", "SHOW DATABASES;"] # Alternative healthcheck
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
    environment:
      MARIADB_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password" # openssl rand -base64 20 | sudo docker secret create db_root_password -
      MARIADB_DATABASE: ${APP_DATABASE_NAME:-app}
      MARIADB_USER: ${APP_MYSQL_USER:-app}
      MARIADB_PASSWORD: ${APP_MYSQL_PASSWORD:-secret}
      MARIADB_ROOT_HOST: "%"
      TZ: ${APP_TIMEZONE:-America/Sao_Paulo}
    secrets:
      - db_root_password
    ports:
      - ${MYSQL_PORT:-3306}:3306
    expose:
      - 3306
    volumes:
      - ${MARIADBDATA_PATH:-/tmp/mysql}:/var/lib/mysql
      - $PWD/services/mariadb/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    networks:
      - ${APP_NETWORK_NAME:-app_network}
  dbadmin:
    extends:
      file: $PWD/services/phpmyadmin/docker-compose.yml
      service: dbadmin
    depends_on: 
      - db
secrets:
  db_root_password:
    file: $PWD/docker-data/mariadb/db_root_password.txt
networks:
  app_network:
    name: ${APP_NETWORK_NAME:-app_network}
    driver: bridge
